services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=thisispass
    ports:
      - 8081:8081
    depends_on:
      - redis
<<<<<<< HEAD
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: thisispass
      POSTGRES_USER: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080  
       
=======
    
>>>>>>> 346ef7eeccc65ff0c4c1a8867e7d870c43fadce8
volumes:
  redis-data: